### ISSUE TITLE
Inconsistências na documentação para Devs

### ISSUE THREAD

**Issue by leonardoteck** [zrp/challenges#8]
Encontrei algumas inconsistências na documentação do desafio para Devs (https://zrpaplicacoes.github.io/challenges/dev/) que podem dificultar um pouco a solução.

1. Ao que me parece, é necessário usar o socket.io para receber os dados do socket, e isso **não está escrito na documentação.**

- Não dá resultado:

```javascript
const net = require('net');
const client = new net.Socket();
client.connect(443, 'https://zrp-challenge-socket.herokuapp.com', () => {
    console.log('Connected');
});
client.on('occurrence', data => console.log('occurrence: ' + data));
client.on('data', data => console.log('data: ' + data));
client.on('close', () => console.log('Connection closed'));
```

- Dá resultado:

```javascript
const io = require('socket.io-client');
const socket = io('https://zrp-challenge-socket.herokuapp.com:443');
socket.on('connect', () => console.log('Connected'));
socket.on('occurrence', data => console.log('Received: ' + data));
socket.on('disconnect', () => console.log('Connection closed'));
```

2. Há inconsistências na nomenclatura do nível das ameaças:

- No texto diz: "Ameaças Nível Gold, Silver, Copper e Wood."
- No código de exemplo da documentação mostra:
```javascript
{
    location: {
        lat: -5.836597,
        lng: -35.236007,
    },
    dangerLevel: 'S',
    monsterName: 'Black Dragon',
}
```
- O socket retorna ameaças com níveis de nomes: Wolf, Tiger, Dragon e God.

3. A estrutura do objeto na documentação difere da estrutura enviada pelo socket:

- Na documentação location é um objeto:
```javascript
{
    location: {
        lat: -5.836597,
        lng: -35.236007,
    },
    dangerLevel: 'S',
    monsterName: 'Black Dragon',
}
```
- No socket location é um array:
```javascript
{
  "location": [
    {
      "lat": -23.67276026092443,
      "lng": -40.4489496079259
    }
  ],
  "dangerLevel": "God",
  "monsterName": "The Slender Rot Lion"
}
```

**Comment by RafaelTCostella** [comment]
Boa @leonardoteck documentação atualizada! Valeu pelo feedback :)
